### ISSUE TITLE
Device not registering in Urban Airship

### ISSUE THREAD

**Issue by mikelinden1** [Essent/nativescript-urban-airship#15]
Hi there,

I have a NativeScript Angular app that I'm trying to integrate Urban Airship push notifications in. In the app I am able to turn on the notifications using this code:

`NsUrbanairship.getInstance().notificationOptIn().then(() => {
            NsUrbanairship.getInstance().registerUser('testuser1');
});`

But the device never shows in the UA dashboard and I do not receive notifications. I can verify the opt in status using `NsUrbanairship.getInstance().isOptIn();` which returns `true`

**Comment by spike1292** [comment]
Cool you are using our plugin! Just took a look at our documentation and I noticed it's a little brief and slightly outdated. So if you are missing pieces or wrong documentation let me know so I can fix it. 

To help you with your current problem I would like to know which platform you have tested and what how your console output looks like.

Also what helped us a lot with testing our Urban Airship configuration was using the demo app in this project.
